# Pod でSecret を参照する例
apiVersion: v1
kind: Pod
metadata:
  name: pod-load-secret
spec:
  containers:
  - name: pod-load-secret
    image: busybox

    # Secret に設定されたkey-value を環境変数として読み込む
    envFrom:
      - secretRef:
          name: secret-test001 # Secret の設定ファイルの、 metadata.name と一致させる
    
    # 読み取り専用ボリュームとして、vloumes で定義しておいたSecret をマウントする
    volumeMounts:
      - name: secret-volume-test002
        mountPath: /etc/secret # Secret の内容をマウントするディレクトリを指定

    # Secret で読み込んでいる内容を表示する
    command: [
      "sh", "-c",
      "echo $SECRET_ENV01 && echo $SECRET_ENV02 && cat /etc/secret/secret-data.csv && cat /etc/secret/plaintext-secret-data.csv && sleep 600"
    ]

  # Secret をマウントするためのボリュームを定義
  volumes:
    - name: secret-volume-test002 # ボリューム名を指定
      secret:
        secretName: secret-test002 # Secret の設定ファイルの、 metadata.name と一致させる
