# Secret で環境変数を設定するサンプル
# Pod の spec.containers.envfrom で Secret を参照する
apiVersion: v1
kind: Secret
metadata:
  name: secret-test001
  creationTimestamp: null
data: # Secret に設定するデータを記述
  # SECRET_ENV01 という環境変数を設定
  SECRET_ENV01: c2VjcmV0X3ZhbHVlMDAx # base64 でエンコードした値を設定する
stringData: # Secret に設定するデータを記述、平文で値を設定する
  # SECRET_ENV02 という環境変数を設定
  SECRET_ENV02: secret_value002 # 平文で値を設定する
