# Secret で設定ファイルを記述するサンプル
# Pod の spec.containers.volumeMounts で Secret を参照し、volumes でマウントする
apiVersion: v1
kind: Secret
metadata:
  name: secret-test002
  creationTimestamp: null
data: # Secret に設定するデータを記述
  # base64 でエンコードした値を設定する
  secret-data.csv: bmFtZSxlbWFpbCxwYXNzd29yZApKb2huIERvZSxqb2huLWRvZUBleGFtcGxlLmNvbSxzZWNyZXQxMjMKTWFyeSBKYW5lLG1hcnktamFuZUBleGFtcGUuY29tLHNlY3JldDQ1NgpTdWUgU21pdGgsc3VlLXNtaXRoQGV4YW1wbGUuY29tLHNlY3JldDc4OQo=
stringData: # Secret に設定するデータを記述、平文で値を設定する
  plaintext-secret-data.csv: |
    name,email,password
    Eliza Hamilton,eliza-hamilton@example.com,pass123
    Kate Watson,kate-watson@example.com,password456
    Tim Larkin,tim-larkin@example.com,password789
